#!/bin/bash

# Release script for Beaver project
# Creates git tags and triggers GitHub release workflow

set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=ci-common.sh
source "${SCRIPT_DIR}/ci-common.sh"

# Show usage information
usage() {
    cat << EOF
Release Script for Beaver

Usage: $0 <release-type>

Release Types:
    patch    Increment patch version (x.y.Z)
    minor    Increment minor version (x.Y.0)
    major    Increment major version (X.0.0)

Examples:
    $0 patch   # v1.0.0 -> v1.0.1
    $0 minor   # v1.0.0 -> v1.1.0
    $0 major   # v1.0.0 -> v2.0.0

Environment Variables:
    DRY_RUN    If set to 'true', shows what would be done without executing
    VERBOSE    If set to 'true', enables verbose output
EOF
}

# Parse command line arguments
parse_args() {
    if [[ $# -ne 1 ]]; then
        log_error "Exactly one argument required"
        usage
        exit 1
    fi
    
    RELEASE_TYPE="$1"
    
    case "$RELEASE_TYPE" in
        patch|minor|major)
            ;;
        *)
            log_error "Invalid release type: $RELEASE_TYPE"
            log_info "Valid types: patch, minor, major"
            exit 1
            ;;
    esac
}

# Get current version from git tags
get_current_version() {
    local current_tag
    current_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    
    # Remove 'v' prefix if present
    current_tag="${current_tag#v}"
    
    echo "$current_tag"
}

# Calculate next version based on release type
calculate_next_version() {
    local current="$1"
    local type="$2"
    
    # Parse current version
    local version_regex='^([0-9]+)\.([0-9]+)\.([0-9]+)$'
    if [[ ! $current =~ $version_regex ]]; then
        log_error "Invalid version format: $current"
        log_info "Expected format: x.y.z"
        return 1
    fi
    
    local major="${BASH_REMATCH[1]}"
    local minor="${BASH_REMATCH[2]}"
    local patch="${BASH_REMATCH[3]}"
    
    # Calculate next version
    case "$type" in
        patch)
            patch=$((patch + 1))
            ;;
        minor)
            minor=$((minor + 1))
            patch=0
            ;;
        major)
            major=$((major + 1))
            minor=0
            patch=0
            ;;
    esac
    
    echo "${major}.${minor}.${patch}"
}

# Create git tag
create_git_tag() {
    local version="$1"
    local tag="v${version}"
    
    log_info "Creating git tag: $tag"
    
    # Check if tag already exists
    if git rev-parse "$tag" >/dev/null 2>&1; then
        log_error "Tag $tag already exists"
        return 1
    fi
    
    # Create annotated tag
    local tag_message
    tag_message="🦫 Beaver $tag

🚀 Release created via automated release script

Generated by: $(whoami)@$(hostname)
Generated at: $(date)

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "DRY RUN: Would create tag $tag"
        log_debug "Tag message: $tag_message"
    else
        if git tag -a "$tag" -m "$tag_message"; then
            log_success "Created tag: $tag"
        else
            log_error "Failed to create tag: $tag"
            return 1
        fi
    fi
    
    return 0
}

# Push tag to remote
push_tag() {
    local version="$1"
    local tag="v${version}"
    
    log_info "Pushing tag to remote: $tag"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "DRY RUN: Would push tag $tag"
    else
        if git push origin "$tag"; then
            log_success "Pushed tag: $tag"
            log_info "GitHub release workflow will be triggered automatically"
            log_info "Monitor progress at: https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:/]\([^.]*\).*/\1/')/actions"
        else
            log_error "Failed to push tag: $tag"
            return 1
        fi
    fi
    
    return 0
}

# Check prerequisites
check_prerequisites() {
    # Check if we're in a git repository
    if ! git rev-parse --git-dir >/dev/null 2>&1; then
        log_error "Not in a git repository"
        return 1
    fi
    
    # Check if working directory is clean
    if [[ -n "$(git status --porcelain)" ]]; then
        log_error "Working directory is not clean"
        log_info "Please commit or stash your changes before creating a release"
        return 1
    fi
    
    # Check if we're on main branch
    local current_branch
    current_branch=$(git branch --show-current)
    if [[ "$current_branch" != "main" ]]; then
        log_warn "Not on main branch (current: $current_branch)"
        log_info "Releases are typically created from main branch"
        
        # Ask for confirmation if not in dry-run mode
        if [[ "${DRY_RUN:-false}" != "true" ]]; then
            read -p "Continue anyway? (y/N): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                log_info "Release cancelled"
                return 1
            fi
        fi
    fi
    
    # Check if remote exists
    if ! git remote get-url origin >/dev/null 2>&1; then
        log_error "No 'origin' remote found"
        return 1
    fi
    
    return 0
}

# Show release summary
show_release_summary() {
    local current_version="$1"
    local next_version="$2"
    local release_type="$3"
    
    log_section "Release Summary"
    log_info "Release Type: $release_type"
    log_info "Current Version: v$current_version"
    log_info "Next Version: v$next_version"
    log_info "Repository: $(git config --get remote.origin.url | sed 's/.*github.com[:/]\([^.]*\).*/\1/')"
    log_info "Branch: $(git branch --show-current)"
    log_info "Commit: $(git rev-parse --short HEAD)"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_warn "DRY RUN MODE - No actual changes will be made"
    fi
}

# Main release process
main() {
    parse_args "$@"
    
    log_section "Beaver Release Process"
    
    # Check prerequisites
    check_prerequisites || exit 1
    
    # Get current version and calculate next
    local current_version
    current_version=$(get_current_version)
    
    local next_version
    next_version=$(calculate_next_version "$current_version" "$RELEASE_TYPE")
    
    # Show summary
    show_release_summary "$current_version" "$next_version" "$RELEASE_TYPE"
    
    # Confirm unless dry-run
    if [[ "${DRY_RUN:-false}" != "true" ]]; then
        echo
        read -p "Proceed with release? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Release cancelled"
            exit 0
        fi
    fi
    
    # Create and push tag
    create_git_tag "$next_version" || exit 1
    push_tag "$next_version" || exit 1
    
    log_success "Release v$next_version completed successfully!"
    
    if [[ "${DRY_RUN:-false}" != "true" ]]; then
        log_info "Next steps:"
        log_info "  1. Monitor GitHub Actions for release workflow"
        log_info "  2. Check GitHub Releases page for binary artifacts"
        log_info "  3. Update documentation if needed"
        log_info "  4. Announce release to users"
    fi
}

# Execute main function
main "$@"