name: 🚀 機能リクエスト
description: 新機能の提案をしてください
title: "[Feature] "
labels: ["enhancement", "triage"]
assignees: ["nyasuto"]

body:
  - type: markdown
    attributes:
      value: |
        機能リクエストをありがとうございます。以下の情報を提供してください。

  - type: textarea
    id: feature-description
    attributes:
      label: 機能の説明
      description: 提案する機能の詳細な説明
      placeholder: どのような機能を追加したいかを説明してください
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 解決したい問題
      description: この機能が解決する問題や課題
      placeholder: 現在どのような問題や不便さがありますか？
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案する解決策
      description: 機能の実装方法やアプローチ
      placeholder: どのように実装すべきかのアイデアがあれば説明してください
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる解決策
      placeholder: 他のアプローチや代替案があれば説明してください

  - type: textarea
    id: use-cases
    attributes:
      label: 使用例
      description: この機能の具体的な使用例
      placeholder: |
        1. ユーザーが...したいとき
        2. ...の場合に
        3. ...のシナリオで
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度
      options:
        - Low (低) - 将来的に追加したい
        - Medium (中) - 数ヶ月以内に追加したい
        - High (高) - 近いうちに必要
        - Critical (緊急) - すぐに必要
      default: 1
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 実装の複雑さ（推定）
      description: 実装の難易度の推定
      options:
        - Simple (簡単) - 数時間から1日
        - Medium (普通) - 数日から1週間
        - Complex (複雑) - 数週間
        - Very Complex (非常に複雑) - 1ヶ月以上
      default: 1

  - type: textarea
    id: technical-requirements
    attributes:
      label: 技術的要件
      description: 実装に必要な技術的要素
      placeholder: |
        - 新しい依存関係
        - APIの変更
        - データベーススキーマの変更
        - UI/UXの変更

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 受け入れ基準
      description: 機能が完成したと判断する基準
      placeholder: |
        - [ ] 条件1が満たされている
        - [ ] 条件2が実装されている
        - [ ] テストが作成されている
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: スクリーンショット、モックアップ、参考資料など

  - type: checkboxes
    id: terms
    attributes:
      label: チェックリスト
      options:
        - label: 既存のissueを検索しましたが、同様の機能リクエストは見つかりませんでした
          required: true
        - label: この機能が既存の機能と重複していないことを確認しました
          required: true
        - label: この機能がプロジェクトの目標に合致していると思います
          required: true