# Classification Rules Configuration
# This file defines the rules used by the issue classification system.
# Rules are applied in order and can be customized based on project needs.

version: "1.0.0"
minConfidence: 0.7
maxCategories: 3
enableAutoClassification: true
enablePriorityEstimation: true

# Category weights (0.0 to 1.0)
categoryWeights:
  bug: 1.0
  security: 1.0
  feature: 0.8
  enhancement: 0.7
  performance: 0.8
  documentation: 0.5
  question: 0.4
  duplicate: 0.3
  invalid: 0.3
  wontfix: 0.3
  help-wanted: 0.6
  good-first-issue: 0.5
  refactor: 0.6
  test: 0.5
  ci-cd: 0.6
  dependencies: 0.5

# Priority weights (0.0 to 1.0)
priorityWeights:
  critical: 1.0
  high: 0.8
  medium: 0.6
  low: 0.4
  backlog: 0.2

# Classification rules
rules:
  - id: "bug-detection"
    name: "Bug Detection"
    description: "Detects bug reports based on common keywords and patterns"
    category: "bug"
    priority: "high"
    weight: 0.9
    enabled: true
    conditions:
      titleKeywords:
        - "bug"
        - "error"
        - "issue" 
        - "problem"
        - "broken"
        - "fix"
        - "crash"
        - "fails"
        - "doesn't work"
        - "not working"
      bodyKeywords:
        - "error"
        - "exception"
        - "stack trace"
        - "reproduce"
        - "expected"
        - "actual"
        - "traceback"
        - "failure"
      titlePatterns:
        - "/\\b(bug|error|issue|fix)\\b/i"
        - "/\\b(crash|fail)\\b/i"
      bodyPatterns:
        - "/steps to reproduce/i"
        - "/expected behavior/i"
        - "/actual behavior/i"
        - "/error message/i"

  - id: "feature-request"
    name: "Feature Request"
    description: "Identifies feature requests and new functionality proposals"
    category: "feature"
    priority: "medium"
    weight: 0.8
    enabled: true
    conditions:
      titleKeywords:
        - "feature"
        - "add"
        - "implement"
        - "support"
        - "request"
        - "proposal"
        - "new"
        - "allow"
        - "enable"
      bodyKeywords:
        - "would like"
        - "could we"
        - "suggestion"
        - "proposal"
        - "feature"
        - "functionality"
        - "capability"
      titlePatterns:
        - "/\\b(add|implement|support)\\b/i"
        - "/\\bfeature\\b/i"
        - "/\\brequest\\b/i"

  - id: "enhancement"
    name: "Enhancement"
    description: "Identifies improvements to existing functionality"
    category: "enhancement"
    priority: "medium"
    weight: 0.7
    enabled: true
    conditions:
      titleKeywords:
        - "improve"
        - "enhance"
        - "better"
        - "optimize"
        - "update"
        - "upgrade"
        - "refine"
        - "polish"
      bodyKeywords:
        - "improvement"
        - "enhancement"
        - "optimization"
        - "performance"
        - "better"
        - "more efficient"
      titlePatterns:
        - "/\\b(improve|enhance|better|optimize)\\b/i"
        - "/\\b(upgrade|update)\\b/i"

  - id: "documentation"
    name: "Documentation"
    description: "Identifies documentation-related issues"
    category: "documentation"
    priority: "low"
    weight: 0.8
    enabled: true
    conditions:
      titleKeywords:
        - "docs"
        - "documentation"
        - "readme"
        - "guide"
        - "tutorial"
        - "example"
        - "manual"
        - "help"
        - "explain"
      bodyKeywords:
        - "documentation"
        - "docs"
        - "readme"
        - "guide"
        - "tutorial"
        - "examples"
        - "clarification"
      titlePatterns:
        - "/\\b(docs?|documentation|readme)\\b/i"
        - "/\\b(guide|tutorial|example)\\b/i"

  - id: "question"
    name: "Question"
    description: "Identifies questions and help requests"
    category: "question"
    priority: "low"
    weight: 0.6
    enabled: true
    conditions:
      titleKeywords:
        - "how"
        - "why"
        - "what"
        - "question"
        - "help"
        - "clarification"
        - "understand"
        - "explain"
      bodyKeywords:
        - "question"
        - "help"
        - "how do i"
        - "how can i"
        - "clarification"
        - "confused"
        - "understand"
      titlePatterns:
        - "/\\?$/"
        - "/\\bhow\\b/i"
        - "/\\bwhy\\b/i"
        - "/\\bwhat\\b/i"

  - id: "security"
    name: "Security"
    description: "Identifies security-related issues"
    category: "security"
    priority: "critical"
    weight: 1.0
    enabled: true
    conditions:
      titleKeywords:
        - "security"
        - "vulnerability"
        - "exploit"
        - "xss"
        - "csrf"
        - "injection"
        - "attack"
        - "malicious"
        - "breach"
      bodyKeywords:
        - "security"
        - "vulnerability"
        - "exploit"
        - "attack"
        - "malicious"
        - "unauthorized"
        - "privilege"
        - "sensitive data"
      titlePatterns:
        - "/\\b(security|vulnerability|exploit)\\b/i"
        - "/\\b(xss|csrf|sql injection)\\b/i"

  - id: "performance"
    name: "Performance"
    description: "Identifies performance-related issues"
    category: "performance"
    priority: "medium"
    weight: 0.8
    enabled: true
    conditions:
      titleKeywords:
        - "performance"
        - "slow"
        - "fast"
        - "speed"
        - "optimization"
        - "memory"
        - "cpu"
        - "latency"
        - "timeout"
      bodyKeywords:
        - "performance"
        - "slow"
        - "fast"
        - "optimization"
        - "memory"
        - "cpu"
        - "latency"
        - "bottleneck"
      titlePatterns:
        - "/\\b(slow|fast|performance|optimization)\\b/i"
        - "/\\b(memory|cpu|latency)\\b/i"

  - id: "refactor"
    name: "Refactor" 
    description: "Identifies code refactoring tasks"
    category: "refactor"
    priority: "medium"
    weight: 0.6
    enabled: true
    conditions:
      titleKeywords:
        - "refactor"
        - "cleanup"
        - "reorganize"
        - "restructure"
        - "clean up"
        - "code quality"
        - "tech debt"
      bodyKeywords:
        - "refactor"
        - "cleanup"
        - "code quality"
        - "technical debt"
        - "maintainability"
        - "readability"
      titlePatterns:
        - "/\\b(refactor|cleanup|restructure)\\b/i"
        - "/\\btech debt\\b/i"

  - id: "test"
    name: "Test"
    description: "Identifies testing-related issues"
    category: "test"
    priority: "low"
    weight: 0.5
    enabled: true
    conditions:
      titleKeywords:
        - "test"
        - "testing"
        - "spec"
        - "unit test"
        - "integration test"
        - "coverage"
        - "mock"
      bodyKeywords:
        - "test"
        - "testing"
        - "spec"
        - "coverage"
        - "mock"
        - "assertion"
      titlePatterns:
        - "/\\btest\\b/i"
        - "/\\bcoverage\\b/i"

  - id: "dependencies"
    name: "Dependencies"
    description: "Identifies dependency-related issues"
    category: "dependencies"
    priority: "low"
    weight: 0.5
    enabled: true
    conditions:
      titleKeywords:
        - "dependency"
        - "dependencies"
        - "npm"
        - "yarn"
        - "package"
        - "update"
        - "upgrade"
        - "version"
      bodyKeywords:
        - "dependency"
        - "package"
        - "npm"
        - "yarn"
        - "version"
        - "update"
        - "upgrade"
      titlePatterns:
        - "/\\b(dependency|dependencies|package)\\b/i"
        - "/\\b(npm|yarn)\\b/i"

  - id: "ci-cd"
    name: "CI/CD"
    description: "Identifies CI/CD pipeline issues"
    category: "ci-cd"
    priority: "medium"
    weight: 0.6
    enabled: true
    conditions:
      titleKeywords:
        - "ci"
        - "cd"
        - "pipeline"
        - "build"
        - "deploy"
        - "deployment"
        - "github actions"
        - "workflow"
      bodyKeywords:
        - "pipeline"
        - "build"
        - "deployment"
        - "ci"
        - "cd"
        - "github actions"
        - "workflow"
      titlePatterns:
        - "/\\b(ci|cd|pipeline|build|deploy)\\b/i"
        - "/\\bgithub actions\\b/i"