package wiki

import (
	"fmt"
	"text/template"
)

// TemplateManager manages Wiki generation templates
type TemplateManager struct {
	templates map[string]*template.Template
}

// NewTemplateManager creates a new template manager
func NewTemplateManager() *TemplateManager {
	tm := &TemplateManager{
		templates: make(map[string]*template.Template),
	}
	tm.loadDefaultTemplates()
	return tm
}

// LoadTemplate loads a template from string
func (tm *TemplateManager) LoadTemplate(name, content string) error {
	tmpl, err := template.New(name).Parse(content)
	if err != nil {
		return fmt.Errorf("failed to parse template %s: %w", name, err)
	}
	tm.templates[name] = tmpl
	return nil
}

// GetTemplate returns a template by name
func (tm *TemplateManager) GetTemplate(name string) (*template.Template, bool) {
	tmpl, exists := tm.templates[name]
	return tmpl, exists
}

// loadDefaultTemplates loads built-in templates
func (tm *TemplateManager) loadDefaultTemplates() {
	// Issues Summary Template
	_ = tm.LoadTemplate("issues-summary", issuesSummaryTemplate) //nolint:errcheck // Default templates

	// Troubleshooting Guide Template
	_ = tm.LoadTemplate("troubleshooting", troubleshootingTemplate) //nolint:errcheck // Default templates

	// Learning Path Template
	_ = tm.LoadTemplate("learning-path", learningPathTemplate) //nolint:errcheck // Default templates

	// Index Template
	_ = tm.LoadTemplate("index", indexTemplate) //nolint:errcheck // Default templates

	// Statistics Template
	_ = tm.LoadTemplate("statistics", statisticsTemplate) //nolint:errcheck // Default templates

	// Label Analysis Template
	_ = tm.LoadTemplate("label-analysis", labelAnalysisTemplate) //nolint:errcheck // Default templates

	// Quick Reference Template
	_ = tm.LoadTemplate("quick-reference", quickReferenceTemplate) //nolint:errcheck // Default templates

	// Processing Logs Template
	_ = tm.LoadTemplate("processing-logs", processingLogsTemplate) //nolint:errcheck // Default templates
}

// RegisterTemplate registers a custom template
func (tm *TemplateManager) RegisterTemplate(name, content string) error {
	return tm.LoadTemplate(name, content)
}

// ListTemplates returns all available template names
func (tm *TemplateManager) ListTemplates() []string {
	var names []string
	for name := range tm.templates {
		names = append(names, name)
	}
	return names
}

// Template content definitions

const issuesSummaryTemplate = `# 📋 {{.ProjectName}} - Issues Summary

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 📊 Overview

- **Total Issues**: {{.TotalIssues}}
- **Open Issues**: {{.OpenIssues}}
- **Closed Issues**: {{.ClosedIssues}}
- **AI Processor**: {{.AIProcessor}}
- **Beaver Version**: {{.BeaverVersion}}

## 🤖 AI Classification Summary

{{if gt .ClassificationStats.TotalClassified 0}}
- **Total Classified**: {{.ClassificationStats.TotalClassified}} / {{.TotalIssues}}
- **Average Confidence**: {{printf "%.2f" .ClassificationStats.AverageConfidence}}
- **High Confidence (≥0.8)**: {{.ClassificationStats.HighConfidenceCount}}
- **Low Confidence (<0.5)**: {{.ClassificationStats.LowConfidenceCount}}

### 📊 Categories Distribution
{{range $category, $count := .ClassificationStats.ByCategory}}
- **{{$category}}**: {{$count}} issue(s)
{{end}}

### 🔧 Classification Methods
{{range $method, $count := .ClassificationStats.ByMethod}}
- **{{$method}}**: {{$count}} issue(s)
{{end}}

### 🏷️ Most Common Tags
{{if .ClassificationStats.MostCommonTags}}{{range $i, $tag := .ClassificationStats.MostCommonTags}}{{if $i}}, {{end}}` + "`{{$tag}}`" + `{{end}}{{end}}
{{else}}
- **No AI classification data available**
- Run ` + "`beaver classify`" + ` to generate AI classifications
{{end}}

## 📝 Issues List

{{range .Issues}}
### 🔸 Issue #{{.Number}}: {{.Title}}

**Status**: {{if eq .State "open"}}🟡 Open{{else}}✅ Closed{{end}}
**Created**: {{.CreatedAt.Format "2006-01-02"}}
**Updated**: {{.UpdatedAt.Format "2006-01-02"}}
**Author**: {{.User}}

{{if .Classification}}
**🤖 AI Classification**:
- **Category**: ` + "`{{.Classification.Category}}`" + ` ({{printf "%.2f" .Classification.Confidence}} confidence)
- **Method**: {{.Classification.Method}}
- **Reasoning**: {{.Classification.Reasoning}}
{{if .Classification.SuggestedTags}}- **Suggested Tags**: {{range $i, $tag := .Classification.SuggestedTags}}{{if $i}}, {{end}}` + "`{{$tag}}`" + `{{end}}{{end}}
- **Classified**: {{.Classification.ClassifiedAt.Format "2006-01-02 15:04"}}
{{end}}

{{if .Labels}}**Labels**: {{range $i, $label := .Labels}}{{if $i}}, {{end}}` + "`{{$label}}`" + `{{end}}{{end}}

**Description**:
{{if gt (len .Body) 200}}{{slice .Body 0 200}}...{{else}}{{.Body}}{{end}}

{{if .Comments}}
**Comments**: {{len .Comments}} comment(s)
{{end}}

---

{{end}}

## 🔗 Navigation

- [🏠 Home](Home)
- [🛠️ Troubleshooting Guide](Troubleshooting-Guide)
- [📚 Learning Path](Learning-Path)

---

**📌 Note**: This summary was automatically generated from GitHub Issues using Beaver AI processing.
`

const troubleshootingTemplate = `# 🛠️ {{.ProjectName}} - Troubleshooting Guide

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 📋 Overview

This guide contains solutions and troubleshooting information extracted from **{{len .SolvedIssues}} solved issues**.

## 🔧 Common Error Patterns

{{range .CommonErrors}}
### ❌ {{.Pattern}}

**Description**: {{.Description}}
**Frequency**: {{.Frequency}} occurrence(s)

**Solutions**:
{{range .Solutions}}
- {{.}}
{{end}}

---

{{end}}

## ✅ Documented Solutions

{{range .Solutions}}
### 💡 {{.Title}}

{{.Description}}

**Steps**:
{{range .Steps}}
1. {{.}}
{{end}}

**Related Issues**: {{range $i, $issue := .RelatedIssues}}{{if $i}}, {{end}}#{{$issue}}{{end}}

---

{{end}}

## 📋 Solved Issues Reference

{{range .SolvedIssues}}
### ✅ #{{.Number}}: {{.Title}}

**Solved**: {{.UpdatedAt.Format "2006-01-02"}}
**Resolution**: {{if gt (len .Body) 150}}{{slice .Body 0 150}}...{{else}}{{.Body}}{{end}}

{{if .Labels}}**Tags**: {{range $i, $label := .Labels}}{{if $i}}, {{end}}` + "`{{$label}}`" + `{{end}}{{end}}

{{end}}

## 🚨 Quick Fixes

### Common Issues
- Check configuration files
- Verify API keys and environment variables
- Review log files for detailed error messages
- Ensure all dependencies are properly installed

### Debug Steps
1. Enable debug logging
2. Check system requirements
3. Verify network connectivity
4. Test with minimal configuration

## 🔗 Navigation

- [🏠 Home](Home)
- [📋 Issues Summary](Issues-Summary)
- [📚 Learning Path](Learning-Path)

---

**📌 Note**: Solutions are extracted from resolved GitHub Issues. For detailed context, refer to the original issue numbers.
`

const learningPathTemplate = `# 📚 {{.ProjectName}} - Learning Path

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 🎯 Development Journey

This learning path is extracted from the project's evolution through GitHub Issues and implementation milestones.

## 🏁 Milestones

{{range .Milestones}}
### 🚩 {{.Name}}

{{.Description}}

{{if .CompletedAt}}**Completed**: {{.CompletedAt.Format "2006-01-02"}}{{else}}**Status**: In Progress{{end}}

**Issues**: {{len .Issues}} issue(s)
{{range .Issues}}
- [#{{.Number}}: {{.Title}}](../issues/{{.Number}})
{{end}}

**Key Learnings**:
{{range .Learnings}}
- {{.}}
{{end}}

---

{{end}}

## 💻 Technologies & Skills

{{range .Technologies}}
### 🔧 {{.Name}}

{{.Description}}

**Used in**:
{{range .UsedIn}}
- {{.}}
{{end}}

**Resources**:
{{range .Resources}}
- {{.}}
{{end}}

---

{{end}}

## 🎯 Learning Goals

{{range .LearningGoals}}
### 📖 {{.Title}}

{{.Description}}

**Status**: {{.Status}}
**Progress**: {{.Progress}}%

{{if eq .Status "Completed"}}✅{{else if eq .Status "In Progress"}}🔄{{else}}⏳{{end}} {{.Progress}}% Complete

**Related Issues**: {{range $i, $issue := .RelatedIssues}}{{if $i}}, {{end}}#{{$issue}}{{end}}

---

{{end}}

## 📈 Growth Areas

### Technical Skills
- Software architecture and design patterns
- API development and integration
- Testing and quality assurance
- DevOps and deployment strategies

### Soft Skills
- Problem-solving methodology
- Documentation and communication
- Project planning and execution
- Code review and collaboration

## 🎓 Next Steps

1. **Review completed milestones** for key insights
2. **Identify knowledge gaps** from current issues
3. **Plan learning objectives** for upcoming features
4. **Document lessons learned** for future reference

## 🔗 Navigation

- [🏠 Home](Home)
- [📋 Issues Summary](Issues-Summary)
- [🛠️ Troubleshooting Guide](Troubleshooting-Guide)

---

**📌 Note**: This learning path is dynamically generated from project activity and should be reviewed regularly.
`

const indexTemplate = `# 🦫 {{.ProjectName}} - Knowledge Dam

> 🤖 Powered by Beaver AI - Transforming development streams into structured knowledge

Welcome to the **{{.ProjectName}}** knowledge base! This Wiki is automatically generated from GitHub Issues using AI processing to create structured documentation.

## 📚 Documentation Sections

### 📋 [Issues Summary](Issues-Summary)
Complete overview of all GitHub Issues with AI-generated summaries and categorization.

### 🛠️ [Troubleshooting Guide](Troubleshooting-Guide)
Solutions and fixes extracted from resolved issues, organized by problem patterns.

### 📚 [Learning Path](Learning-Path)
Development journey and milestones extracted from project evolution.

## 🤖 AI Processing

This documentation is generated using:
- **OpenAI/Anthropic APIs** for content analysis
- **Pattern recognition** for categorization
- **Semantic analysis** for knowledge extraction
- **Template-based generation** for consistent formatting

## 📊 Statistics

- **Generated**: {{.GeneratedAt.Format "2006-01-02 15:04:05"}}
- **Total Issues**: {{.TotalIssues}}
- **Processing Status**: {{.Status}}
- **Last Update**: {{.LastUpdate.Format "2006-01-02 15:04:05"}}

## 🔄 Auto-Update

This Wiki is automatically updated when:
- New issues are created or updated
- Issues are closed or resolved
- AI processing reveals new patterns
- Project milestones are reached

## 🎯 Purpose

The Beaver Knowledge Dam serves to:
1. **Preserve Knowledge**: Prevent valuable insights from being lost
2. **Accelerate Learning**: Provide structured learning paths
3. **Improve Debugging**: Offer quick access to solutions
4. **Track Progress**: Document development evolution

## 🔧 Configuration

Wiki generation can be customized through:
- Template modifications
- Category definitions
- Processing rules
- Output formats

## 📞 Support

For issues with Wiki generation:
1. Check the [Troubleshooting Guide](Troubleshooting-Guide)
2. Review the original GitHub Issues
3. Verify Beaver AI configuration
4. Submit feedback through project issues

---

**🚀 Ready to explore your project's knowledge! Navigate using the links above.**
`

const statisticsTemplate = `# 📊 {{.ProjectName}} - Statistics Dashboard

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 🧭 Current Location
📊 **Statistics Dashboard**

## 📈 Project Overview

| Metric | Value | Trend |
|--------|-------|-------|
| **Total Issues** | {{.TotalIssues}} | {{if .Trends.IssueGrowth}}📈 +{{.Trends.IssueGrowth}}%{{else}}📊 Stable{{end}} |
| **Open Issues** | {{.OpenIssues}} | {{if gt .OpenIssues 0}}🟡 Active{{else}}✅ Clear{{end}} |
| **Closed Issues** | {{.ClosedIssues}} | {{if .Trends.ResolutionRate}}✅ {{printf "%.1f" .Trends.ResolutionRate}}%{{else}}📊 N/A{{end}} |
| **Resolution Rate** | {{if gt .TotalIssues 0}}{{printf "%.1f" (div (mul .ClosedIssues 100) .TotalIssues)}}%{{else}}0%{{end}} | {{if .Trends.ResolutionImprovement}}📈 Improving{{else}}📊 Stable{{end}} |

## 🏷️ Issue Classification Statistics

{{if .ClassificationStats}}
### AI Classification Overview
- **Total Classified**: {{.ClassificationStats.TotalClassified}} / {{.TotalIssues}} ({{if gt .TotalIssues 0}}{{printf "%.1f" (div (mul .ClassificationStats.TotalClassified 100) .TotalIssues)}}%{{else}}0%{{end}})
- **Average Confidence**: {{printf "%.2f" .ClassificationStats.AverageConfidence}} ({{if ge .ClassificationStats.AverageConfidence 0.8}}🎯 High{{else if ge .ClassificationStats.AverageConfidence 0.6}}⚠️ Medium{{else}}🔴 Low{{end}})
- **High Confidence (≥0.8)**: {{.ClassificationStats.HighConfidenceCount}}
- **Medium Confidence (0.5-0.8)**: {{sub .ClassificationStats.TotalClassified (add .ClassificationStats.HighConfidenceCount .ClassificationStats.LowConfidenceCount)}}
- **Low Confidence (<0.5)**: {{.ClassificationStats.LowConfidenceCount}}

### 📊 Category Distribution
{{if .ClassificationStats.ByCategory}}
| Category | Count | Percentage |
|----------|-------|------------|
{{range $category, $count := .ClassificationStats.ByCategory}}| **{{$category}}** | {{$count}} | {{if gt $.TotalIssues 0}}{{printf "%.1f" (div (mul $count 100) $.TotalIssues)}}%{{else}}0%{{end}} |
{{end}}
{{else}}
| Category | Count | Percentage |
|----------|-------|------------|
| *No classification data* | - | - |
{{end}}

### 🔧 Classification Methods
{{if .ClassificationStats.ByMethod}}
{{range $method, $count := .ClassificationStats.ByMethod}}
- **{{$method}}**: {{$count}} issue(s) ({{if gt $.ClassificationStats.TotalClassified 0}}{{printf "%.1f" (div (mul $count 100) $.ClassificationStats.TotalClassified)}}%{{else}}0%{{end}})
{{end}}
{{else}}
- *No method data available*
{{end}}

### 🏷️ Most Common Tags
{{if .ClassificationStats.MostCommonTags}}
{{range $i, $tag := .ClassificationStats.MostCommonTags}}{{if $i}} • {{end}}` + "`{{$tag}}`" + `{{end}}
{{else}}
*No tags available*
{{end}}
{{else}}
### ⚠️ No Classification Data
AI classification has not been run yet. Use ` + "`beaver classify`" + ` to generate statistics.
{{end}}

## ⏱️ Time-Based Analysis

### 📅 Issue Creation Timeline
{{if .TimeStats}}
| Period | Issues Created | Issues Closed | Net Change |
|--------|----------------|---------------|------------|
{{range .TimeStats.MonthlyData}}
| **{{.Month}}** | {{.Created}} | {{.Closed}} | {{if gt .Created .Closed}}+{{sub .Created .Closed}}{{else if lt .Created .Closed}}-{{sub .Closed .Created}}{{else}}0{{end}} |
{{end}}
{{else}}
| Period | Issues Created | Issues Closed | Net Change |
|--------|----------------|---------------|------------|
| *No timeline data* | - | - | - |
{{end}}

### 📊 Activity Patterns
{{if .ActivityStats}}
- **Most Active Day**: {{.ActivityStats.MostActiveDay}} ({{.ActivityStats.MostActiveDayCount}} issues)
- **Most Active Month**: {{.ActivityStats.MostActiveMonth}} ({{.ActivityStats.MostActiveMonthCount}} issues)
- **Average Issues per Month**: {{printf "%.1f" .ActivityStats.AvgIssuesPerMonth}}
- **Longest Open Issue**: {{.ActivityStats.LongestOpenDays}} days
- **Average Resolution Time**: {{printf "%.1f" .ActivityStats.AvgResolutionDays}} days
{{else}}
- **Activity Analysis**: *Not available - insufficient data*
{{end}}

## 👥 Contributor Statistics

{{if .ContributorStats}}
### Top Contributors
| Contributor | Issues Created | Issues Closed | Contribution % |
|-------------|----------------|---------------|----------------|
{{range .ContributorStats.TopContributors}}
| **{{.Name}}** | {{.IssuesCreated}} | {{.IssuesClosed}} | {{printf "%.1f" .ContributionPercentage}}% |
{{end}}

### Collaboration Metrics
- **Total Contributors**: {{.ContributorStats.TotalContributors}}
- **Active Contributors (last 30 days)**: {{.ContributorStats.ActiveContributors}}
- **New Contributors (last 30 days)**: {{.ContributorStats.NewContributors}}
{{else}}
### Contributor Analysis
*Contributor statistics not available*
{{end}}

## 🎯 Quality Metrics

### Issue Quality Indicators
{{if .QualityStats}}
- **Average Issue Title Length**: {{printf "%.1f" .QualityStats.AvgTitleLength}} characters
- **Average Issue Body Length**: {{printf "%.1f" .QualityStats.AvgBodyLength}} characters
- **Issues with Labels**: {{.QualityStats.IssuesWithLabels}} / {{.TotalIssues}} ({{if gt .TotalIssues 0}}{{printf "%.1f" (div (mul .QualityStats.IssuesWithLabels 100) .TotalIssues)}}%{{else}}0%{{end}})
- **Issues with Comments**: {{.QualityStats.IssuesWithComments}} / {{.TotalIssues}} ({{if gt .TotalIssues 0}}{{printf "%.1f" (div (mul .QualityStats.IssuesWithComments 100) .TotalIssues)}}%{{else}}0%{{end}})
- **Average Comments per Issue**: {{printf "%.1f" .QualityStats.AvgCommentsPerIssue}}
{{else}}
- **Quality Analysis**: *Not available*
{{end}}

### Health Indicators
{{if .HealthStats}}
- **Issue Response Time**: {{printf "%.1f" .HealthStats.AvgResponseTime}} hours {{if le .HealthStats.AvgResponseTime 24}}✅{{else if le .HealthStats.AvgResponseTime 72}}⚠️{{else}}🔴{{end}}
- **Stale Issues (>30 days)**: {{.HealthStats.StaleIssues}} {{if eq .HealthStats.StaleIssues 0}}✅{{else if le .HealthStats.StaleIssues 5}}⚠️{{else}}🔴{{end}}
- **Issues without Labels**: {{.HealthStats.IssuesWithoutLabels}} {{if eq .HealthStats.IssuesWithoutLabels 0}}✅{{else}}⚠️{{end}}
- **Project Health Score**: {{printf "%.0f" .HealthStats.HealthScore}}/100 {{if ge .HealthStats.HealthScore 80}}🟢{{else if ge .HealthStats.HealthScore 60}}🟡{{else}}🔴{{end}}
{{else}}
- **Health Analysis**: *Not available*
{{end}}

## 📈 Trend Analysis

### Growth Trends
{{if .TrendStats}}
- **Issue Creation Trend**: {{if gt .TrendStats.IssueGrowthRate 0}}📈 Growing (+{{printf "%.1f" .TrendStats.IssueGrowthRate}}%/month){{else if lt .TrendStats.IssueGrowthRate 0}}📉 Declining ({{printf "%.1f" .TrendStats.IssueGrowthRate}}%/month){{else}}📊 Stable{{end}}
- **Resolution Trend**: {{if gt .TrendStats.ResolutionTrend 0}}📈 Improving (+{{printf "%.1f" .TrendStats.ResolutionTrend}}%/month){{else if lt .TrendStats.ResolutionTrend 0}}📉 Declining ({{printf "%.1f" .TrendStats.ResolutionTrend}}%/month){{else}}📊 Stable{{end}}
- **Engagement Trend**: {{if gt .TrendStats.EngagementTrend 0}}📈 Increasing{{else if lt .TrendStats.EngagementTrend 0}}📉 Decreasing{{else}}📊 Stable{{end}}
{{else}}
- **Trend Analysis**: *Insufficient data for trend calculation*
{{end}}

### Predictions
{{if .Predictions}}
- **Estimated Issues Next Month**: {{.Predictions.NextMonthIssues}} {{if gt .Predictions.NextMonthIssues .ActivityStats.AvgIssuesPerMonth}}📈{{else if lt .Predictions.NextMonthIssues .ActivityStats.AvgIssuesPerMonth}}📉{{else}}📊{{end}}
- **Predicted Resolution Time**: {{printf "%.1f" .Predictions.AvgResolutionTime}} days
- **Recommended Focus Areas**: {{range $i, $area := .Predictions.FocusAreas}}{{if $i}}, {{end}}{{$area}}{{end}}
{{else}}
- **Predictions**: *Not available*
{{end}}

## 🔧 Technical Insights

### Issue Complexity Analysis
{{if .ComplexityStats}}
- **Simple Issues (quick fixes)**: {{.ComplexityStats.SimpleIssues}} ({{printf "%.1f" .ComplexityStats.SimplePercentage}}%)
- **Medium Issues (features/bugs)**: {{.ComplexityStats.MediumIssues}} ({{printf "%.1f" .ComplexityStats.MediumPercentage}}%)
- **Complex Issues (major features)**: {{.ComplexityStats.ComplexIssues}} ({{printf "%.1f" .ComplexityStats.ComplexPercentage}}%)
- **Average Complexity Score**: {{printf "%.2f" .ComplexityStats.AvgComplexity}}/10
{{else}}
- **Complexity Analysis**: *Not available*
{{end}}

### Technology Mentions
{{if .TechStats}}
| Technology | Mentions | Issues | Trend |
|------------|----------|--------|-------|
{{range .TechStats.Technologies}}
| **{{.Name}}** | {{.Mentions}} | {{.IssueCount}} | {{if gt .Trend 0}}📈{{else if lt .Trend 0}}📉{{else}}📊{{end}} |
{{end}}
{{else}}
| Technology | Mentions | Issues | Trend |
|------------|----------|--------|-------|
| *No technology data* | - | - | - |
{{end}}

## 📋 Action Items & Recommendations

### 🎯 Based on Current Statistics
{{if .Recommendations}}
{{range .Recommendations.Priority}}
#### {{.Level}} Priority
{{range .Items}}
- {{.Description}} (Impact: {{.Impact}})
{{end}}
{{end}}
{{else}}
#### Recommended Actions
- Monitor issue creation and resolution patterns
- Implement AI classification for better categorization
- Focus on reducing average resolution time
- Encourage community engagement through clear issue templates
{{end}}

### 📊 Data Quality Improvements
- Run ` + "`beaver classify`" + ` to enhance AI categorization data
- Encourage contributors to use descriptive labels
- Monitor response times and engagement patterns
- Regularly review and update issue templates

## 🔄 Data Freshness

- **Statistics Generated**: {{.GeneratedAt.Format "2006-01-02 15:04:05"}}
- **Data Range**: {{if .DataRange}}{{.DataRange.StartDate.Format "2006-01-02"}} to {{.DataRange.EndDate.Format "2006-01-02"}}{{else}}All available data{{end}}
- **Next Scheduled Update**: {{if .NextUpdate}}{{.NextUpdate.Format "2006-01-02 15:04:05"}}{{else}}On next wiki generation{{end}}
- **Auto-Update Status**: {{if .AutoUpdate}}✅ Enabled{{else}}⚠️ Manual{{end}}

## 🔗 Navigation

**Related Pages:**
- [🏠 Home](Home) - Main knowledge base index
- [📋 Issues Summary](Issues-Summary) - Detailed issue listing
- [📊 Label Analysis](Label-Analysis) - Tag and categorization insights
- [📚 Quick Reference](Quick-Reference) - Essential project information

**External Links:**
- [📊 GitHub Insights](../pulse) - Native GitHub analytics
- [📋 Issues](../issues) - Live issue tracker
- [🔄 Actions](../actions) - CI/CD pipeline status

---

**📌 Note**: Statistics are automatically calculated from GitHub Issues data. For real-time data, visit the GitHub repository directly.

*Generated with 📊 by Beaver AI Analytics Engine - Transforming data into actionable insights*
`

const labelAnalysisTemplate = `# 🏷️ {{.ProjectName}} - Label Analysis

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 🧭 Current Location
🏷️ **Label Analysis**

## 📊 Label Overview

| Metric | Value | Insight |
|--------|-------|---------|
| **Total Unique Labels** | {{.TotalLabels}} | {{if gt .TotalLabels 20}}🔴 Many{{else if gt .TotalLabels 10}}⚠️ Moderate{{else}}✅ Manageable{{end}} |
| **Most Used Label** | {{if .MostUsedLabel}}` + "`{{.MostUsedLabel.Name}}`" + `{{else}}*None*{{end}} | {{if .MostUsedLabel}}{{.MostUsedLabel.Count}} issues{{else}}N/A{{end}} |
| **Issues with Labels** | {{.IssuesWithLabels}} / {{.TotalIssues}} | {{if gt .TotalIssues 0}}{{printf "%.1f" (div (mul .IssuesWithLabels 100) .TotalIssues)}}% coverage{{else}}0%{{end}} |
| **Issues without Labels** | {{.IssuesWithoutLabels}} | {{if eq .IssuesWithoutLabels 0}}✅ All labeled{{else if lt .IssuesWithoutLabels 5}}⚠️ Few unlabeled{{else}}🔴 Many unlabeled{{end}} |
| **Average Labels per Issue** | {{printf "%.1f" .AvgLabelsPerIssue}} | {{if ge .AvgLabelsPerIssue 2}}📊 Well-categorized{{else}}⚠️ Under-labeled{{end}} |

## 🎨 Label Distribution

### 📈 Most Popular Labels
{{if .Labels}}
| Label | Issues | Percentage | Usage Pattern | Trend |
|-------|--------|------------|---------------|-------|
{{range .Labels}}
| {{if .Color}}<span style="background: #{{.Color}}; color: white; padding: 2px 6px; border-radius: 3px;">{{.Name}}</span>{{else}}` + "`{{.Name}}`" + `{{end}} | {{.Count}} | {{if gt $.TotalIssues 0}}{{printf "%.1f" (div (mul .Count 100) $.TotalIssues)}}%{{else}}0%{{end}} | {{.UsagePattern}} | {{if gt .Trend 0}}📈{{else if lt .Trend 0}}📉{{else}}📊{{end}} |
{{end}}
{{else}}
| Label | Issues | Percentage | Usage Pattern |
|-------|--------|------------|---------------|
| *No labels found* | - | - | - |
{{end}}

### 🎯 Label Categories

{{if .Categories}}
{{range .Categories}}
#### {{.Name}} Category ({{.Count}} labels)
{{if .Description}}*{{.Description}}*{{end}}

**Labels in this category:**
{{range .Labels}}
- {{if .Color}}<span style="background: #{{.Color}}; color: white; padding: 2px 6px; border-radius: 3px;">{{.Name}}</span>{{else}}` + "`{{.Name}}`" + `{{end}} ({{.Count}} issues)
{{end}}

**Usage Statistics:**
- **Total Issues**: {{.TotalIssues}}
- **Percentage of Project**: {{if gt $.TotalIssues 0}}{{printf "%.1f" (div (mul .TotalIssues 100) $.TotalIssues)}}%{{else}}0%{{end}}
- **Average per Issue**: {{printf "%.1f" .AvgPerIssue}}

---
{{end}}
{{else}}
#### No Label Categories Detected
Labels have not been categorized. Consider organizing labels into logical groups such as:
- **Type**: ` + "`bug`" + `, ` + "`feature`" + `, ` + "`enhancement`" + `, ` + "`documentation`" + `
- **Priority**: ` + "`high`" + `, ` + "`medium`" + `, ` + "`low`" + `, ` + "`critical`" + `
- **Status**: ` + "`in-progress`" + `, ` + "`blocked`" + `, ` + "`ready`" + `, ` + "`review`" + `
- **Area**: ` + "`frontend`" + `, ` + "`backend`" + `, ` + "`api`" + `, ` + "`ui/ux`" + `
{{end}}

## 🔍 Label Analysis Deep Dive

### 🏆 Top Performing Labels
{{if .TopPerformingLabels}}
{{range .TopPerformingLabels}}
#### {{if .Color}}<span style="background: #{{.Color}}; color: white; padding: 2px 6px; border-radius: 3px;">{{.Name}}</span>{{else}}` + "`{{.Name}}`" + `{{end}}
{{if .Description}}*{{.Description}}*{{end}}

**Performance Metrics:**
- **Total Usage**: {{.Count}} issues ({{if gt $.TotalIssues 0}}{{printf "%.1f" (div (mul .Count 100) $.TotalIssues)}}%{{else}}0%{{end}} of project)
- **Resolution Rate**: {{printf "%.1f" .ResolutionRate}}% {{if ge .ResolutionRate 80}}✅{{else if ge .ResolutionRate 60}}⚠️{{else}}🔴{{end}}
- **Average Time to Close**: {{printf "%.1f" .AvgTimeToClose}} days
- **Recent Activity**: {{.RecentUsage}} issues in last 30 days {{if gt .RecentUsage 5}}🔥{{else if gt .RecentUsage 2}}📊{{else}}💤{{end}}

**Associated Labels:**
{{if .CommonlyUsedWith}}
{{range .CommonlyUsedWith}}
- ` + "`{{.Name}}`" + ` ({{.CoOccurrenceCount}} times together)
{{end}}
{{else}}
- *Usually used alone*
{{end}}

---
{{end}}
{{else}}
*No detailed label performance data available*
{{end}}

### 🚨 Label Health Indicators

#### ⚠️ Potential Issues
{{if .LabelIssues}}
{{range .LabelIssues}}
- **{{.Type}}**: {{.Description}}
  - **Affected Labels**: {{range $i, $label := .AffectedLabels}}{{if $i}}, {{end}}` + "`{{$label}}`" + `{{end}}
  - **Impact**: {{.Impact}}
  - **Recommendation**: {{.Recommendation}}
{{end}}
{{else}}
✅ **No label health issues detected**
- All labels are being used consistently
- No duplicate or conflicting labels found
- Good label coverage across issues
{{end}}

#### 📊 Quality Metrics
- **Label Consistency Score**: {{printf "%.0f" .LabelConsistencyScore}}/100 {{if ge .LabelConsistencyScore 80}}🟢{{else if ge .LabelConsistencyScore 60}}🟡{{else}}🔴{{end}}
- **Categorization Coverage**: {{printf "%.1f" .CategorizationCoverage}}% {{if ge .CategorizationCoverage 90}}✅{{else if ge .CategorizationCoverage 70}}⚠️{{else}}🔴{{end}}
- **Label Diversity Index**: {{printf "%.2f" .LabelDiversityIndex}} {{if ge .LabelDiversityIndex 0.8}}📊 Good variety{{else if ge .LabelDiversityIndex 0.5}}⚠️ Limited variety{{else}}🔴 Poor variety{{end}}

## ⏰ Temporal Analysis

### 📅 Label Usage Over Time
{{if .TemporalData}}
| Period | New Labels | Most Active Label | Issues Labeled |
|--------|------------|-------------------|----------------|
{{range .TemporalData}}
| **{{.Period}}** | {{.NewLabels}} | {{if .MostActiveLabel}}` + "`{{.MostActiveLabel.Name}}`" + ` ({{.MostActiveLabel.Count}}){{else}}*None*{{end}} | {{.IssuesLabeled}} |
{{end}}
{{else}}
| Period | New Labels | Most Active Label | Issues Labeled |
|--------|------------|-------------------|----------------|
| *No temporal data* | - | - | - |
{{end}}

### 📈 Trending Labels
{{if .TrendingLabels}}
#### 🔥 Hot Labels (Increasing Usage)
{{range .TrendingLabels.Hot}}
- **` + "`{{.Name}}`" + `**: {{if .Description}}{{.Description}} - {{end}}+{{printf "%.1f" .GrowthRate}}% growth ({{.RecentCount}} recent uses)
{{end}}

#### 📉 Declining Labels (Decreasing Usage)
{{range .TrendingLabels.Declining}}
- **` + "`{{.Name}}`" + `**: {{if .Description}}{{.Description}} - {{end}}{{printf "%.1f" .DeclineRate}}% decline ({{.RecentCount}} recent uses)
{{end}}

#### ⭐ Stable Labels (Consistent Usage)
{{range .TrendingLabels.Stable}}
- **` + "`{{.Name}}`" + `**: {{if .Description}}{{.Description}} - {{end}}Consistent {{.AverageUsage}} uses per month
{{end}}
{{else}}
*No trending data available - need more historical data*
{{end}}

## 🎯 Label Effectiveness Analysis

### 🚀 High-Impact Labels
{{if .HighImpactLabels}}
These labels are most effective at helping organize and resolve issues:

{{range .HighImpactLabels}}
#### ` + "`{{.Name}}`" + ` {{if .Impact.Score}}(Impact Score: {{printf "%.1f" .Impact.Score}}/10){{end}}
- **Resolution Efficiency**: {{printf "%.1f" .Impact.ResolutionEfficiency}}% faster than average
- **Community Engagement**: {{printf "%.1f" .Impact.EngagementMultiplier}}x more comments/reactions
- **Discoverability**: {{printf "%.1f" .Impact.DiscoverabilityScore}}/10
- **Why it works**: {{.Impact.Reason}}
{{end}}
{{else}}
*Impact analysis requires more historical data*
{{end}}

### 📊 Label Combination Analysis
{{if .LabelCombinations}}
#### Most Effective Label Combinations
{{range .LabelCombinations}}
**{{range $i, $label := .Labels}}{{if $i}} + {{end}}` + "`{{$label}}`" + `{{end}}**
- **Used Together**: {{.Count}} times
- **Success Rate**: {{printf "%.1f" .SuccessRate}}%
- **Average Resolution Time**: {{printf "%.1f" .AvgResolutionDays}} days
- **Use Case**: {{.UseCase}}
{{end}}
{{else}}
*Combination analysis requires more data*
{{end}}

## 🔧 Label Management Recommendations

### 🎯 Immediate Actions
{{if .Recommendations.Immediate}}
{{range .Recommendations.Immediate}}
#### {{.Priority}} Priority: {{.Title}}
{{.Description}}

**Implementation:**
{{range .Steps}}
1. {{.}}
{{end}}

**Expected Impact**: {{.ExpectedImpact}}
{{end}}
{{else}}
#### ✅ No Immediate Actions Required
Your label system appears to be well-organized and functioning effectively.
{{end}}

### 📋 Long-term Improvements
{{if .Recommendations.LongTerm}}
{{range .Recommendations.LongTerm}}
#### {{.Title}}
{{.Description}}

**Benefits:**
{{range .Benefits}}
- {{.}}
{{end}}

**Effort Level**: {{.EffortLevel}}
{{end}}
{{else}}
#### Suggested Improvements
1. **Standardize Color Scheme**: Use consistent colors for label categories
2. **Add Descriptions**: Provide clear descriptions for all labels
3. **Regular Cleanup**: Review and consolidate similar labels quarterly
4. **Usage Guidelines**: Create documentation for when to use each label
{{end}}

## 📚 Label Best Practices

### ✅ Current Strengths
{{if .BestPractices.Strengths}}
{{range .BestPractices.Strengths}}
- **{{.Area}}**: {{.Description}}
{{end}}
{{else}}
- Label analysis in progress - strengths will be identified with more data
{{end}}

### 🎯 Improvement Areas
{{if .BestPractices.ImprovementAreas}}
{{range .BestPractices.ImprovementAreas}}
- **{{.Area}}**: {{.Description}}
  - *Suggestion*: {{.Suggestion}}
{{end}}
{{else}}
- Continue current labeling practices
- Monitor label usage patterns
- Gather community feedback on label effectiveness
{{end}}

### 📖 Label Guidelines
{{if .LabelGuidelines}}
{{range .LabelGuidelines}}
#### {{.Category}}
{{range .Rules}}
- {{.}}
{{end}}
{{end}}
{{else}}
#### Recommended Label Categories

**🐛 Issue Type**
- ` + "`bug`" + ` - Something isn't working correctly
- ` + "`enhancement`" + ` - New feature or improvement to existing feature
- ` + "`documentation`" + ` - Improvements or additions to documentation
- ` + "`question`" + ` - Further information is requested

**⚡ Priority**
- ` + "`critical`" + ` - Urgent fix required (security, data loss)
- ` + "`high`" + ` - Important feature or significant bug
- ` + "`medium`" + ` - Standard priority items
- ` + "`low`" + ` - Nice to have, when time permits

**🔧 Status**
- ` + "`ready`" + ` - Ready for development
- ` + "`in-progress`" + ` - Currently being worked on
- ` + "`blocked`" + ` - Cannot proceed due to dependencies
- ` + "`review`" + ` - Ready for code review

**🎯 Area**
- ` + "`frontend`" + ` - User interface related
- ` + "`backend`" + ` - Server-side logic
- ` + "`api`" + ` - API design or issues
- ` + "`infrastructure`" + ` - DevOps, deployment, configuration
{{end}}

## 🔄 Data Freshness & Methodology

- **Analysis Generated**: {{.GeneratedAt.Format "2006-01-02 15:04:05"}}
- **Data Period**: {{if .DataRange}}{{.DataRange.StartDate.Format "2006-01-02"}} to {{.DataRange.EndDate.Format "2006-01-02"}}{{else}}All available data{{end}}
- **Total Issues Analyzed**: {{.TotalIssues}}
- **Analysis Method**: {{if .AnalysisMethod}}{{.AnalysisMethod}}{{else}}Statistical analysis with pattern recognition{{end}}

### 📊 Confidence Levels
- **Label Usage Data**: {{if .ConfidenceLevels.Usage}}{{.ConfidenceLevels.Usage}}{{else}}High{{end}}
- **Trend Analysis**: {{if .ConfidenceLevels.Trends}}{{.ConfidenceLevels.Trends}}{{else}}Medium (requires more historical data){{end}}
- **Effectiveness Scores**: {{if .ConfidenceLevels.Effectiveness}}{{.ConfidenceLevels.Effectiveness}}{{else}}Medium{{end}}

## 🔗 Navigation

**Related Pages:**
- [🏠 Home](Home) - Main knowledge base index
- [📊 Statistics Dashboard](Statistics) - Comprehensive project analytics
- [📋 Issues Summary](Issues-Summary) - Detailed issue listing
- [📚 Quick Reference](Quick-Reference) - Essential project information

**External Links:**
- [📋 Issues](../issues) - Live issue tracker
- [🏷️ Labels](../labels) - Manage project labels
- [📊 Insights](../pulse) - GitHub insights and analytics

---

**📌 Note**: Label analysis is based on current GitHub Issues data. For real-time label management, use the GitHub interface.

*Generated with 🏷️ by Beaver AI Label Analysis Engine - Organizing chaos into clarity*
`

const quickReferenceTemplate = `# 📚 {{.ProjectName}} - Quick Reference

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 🧭 Current Location
📚 **Quick Reference**

---

## 🚀 Project Overview

| **Property** | **Details** |
|--------------|-------------|
| **Project Name** | {{.ProjectName}} |
| **Total Issues** | {{.TotalIssues}} ({{.OpenIssues}} open, {{.ClosedIssues}} closed) |
| **Repository** | {{if .Repository}}[{{.Repository}}]({{.RepositoryURL}}){{else}}*Repository information not available*{{end}} |
| **Primary Language** | {{if .PrimaryLanguage}}{{.PrimaryLanguage}}{{else}}*Multiple/Not detected*{{end}} |
| **Last Activity** | {{.LastActivity.Format "2006-01-02"}} |
| **Documentation Coverage** | {{printf "%.1f" .DocumentationCoverage}}% |

---

## 🏷️ Labels Quick Reference

### 🎯 Most Important Labels
{{if .KeyLabels}}
| **Label** | **Description** | **Usage** |
|-----------|----------------|-----------|
{{range .KeyLabels}}
| **{{if .Color}}<span style="background: #{{.Color}}; color: white; padding: 1px 4px; border-radius: 2px;">{{.Name}}</span>{{else}}` + "`{{.Name}}`" + `{{end}}** | {{.Description}} | **{{.Count}}** issues |
{{end}}
{{else}}
| **Label** | **Description** | **Usage** |
|-----------|----------------|-----------|
| *No key labels identified* | - | - |
{{end}}

### 📊 Label Categories
{{if .LabelCategories}}
{{range .LabelCategories}}
- **{{.Name}}**: {{range $i, $label := .Labels}}{{if $i}}, {{end}}` + "`{{$label}}`" + `{{end}}
{{end}}
{{else}}
- No organized label categories detected
{{end}}

---

## 🔧 Common Issue Types

### 🐛 Bug Reports
{{if .BugPatterns}}
{{range .BugPatterns}}
- **{{.Pattern}}**: {{.Description}} ({{.Count}} occurrences)
{{end}}
{{else}}
- No specific bug patterns identified
{{end}}

### ✨ Feature Requests
{{if .FeaturePatterns}}
{{range .FeaturePatterns}}
- **{{.Pattern}}**: {{.Description}} ({{.Count}} requests)
{{end}}
{{else}}
- No specific feature patterns identified
{{end}}

### ❓ Common Questions
{{if .QuestionPatterns}}
{{range .QuestionPatterns}}
- **{{.Topic}}**: {{.Description}} (asked {{.Count}} times)
{{end}}
{{else}}
- No frequently asked questions identified
{{end}}

---

## ⚡ Quick Actions

### 🔍 Search & Filter
` + "```" + `
# Search by label
label:bug label:critical

# Search by state
state:open state:closed

# Search by author
author:username

# Search in title/body
"error message" in:title
"configuration" in:body
` + "```" + `

### 📝 Issue Templates
{{if .IssueTemplates}}
{{range .IssueTemplates}}
#### {{.Name}}
{{.Description}}

**Required Information:**
{{range .RequiredFields}}
- {{.}}
{{end}}
{{end}}
{{else}}
#### Bug Report Template
**Required Information:**
- Clear description of the issue
- Steps to reproduce
- Expected vs actual behavior
- Environment details
- Error messages/logs

#### Feature Request Template
**Required Information:**
- Feature description
- Use case/motivation
- Proposed solution
- Alternative solutions considered
{{end}}

---

## 🎯 Priority Guidelines

### 🔴 Critical Priority
{{if .PriorityGuidelines.Critical}}
{{range .PriorityGuidelines.Critical}}
- {{.}}
{{end}}
{{else}}
- Security vulnerabilities
- Data loss scenarios
- System completely unusable
- Breaking changes affecting all users
{{end}}

### 🟠 High Priority
{{if .PriorityGuidelines.High}}
{{range .PriorityGuidelines.High}}
- {{.}}
{{end}}
{{else}}
- Major functionality broken
- Significant user impact
- Performance degradation
- Important feature requests
{{end}}

### 🟡 Medium Priority
{{if .PriorityGuidelines.Medium}}
{{range .PriorityGuidelines.Medium}}
- {{.}}
{{end}}
{{else}}
- Minor bugs with workarounds
- Feature improvements
- Documentation updates
- Code quality issues
{{end}}

### 🟢 Low Priority
{{if .PriorityGuidelines.Low}}
{{range .PriorityGuidelines.Low}}
- {{.}}
{{end}}
{{else}}
- Nice-to-have features
- Minor UI/UX improvements
- Code cleanup
- Future enhancements
{{end}}

---

## 👥 Key Contributors

### 🏆 Top Contributors
{{if .TopContributors}}
| **Contributor** | **Issues** | **Contributions** |
|-----------------|------------|-------------------|
{{range .TopContributors}}
| **{{.Name}}** | {{.IssueCount}} | {{.ContributionType}} |
{{end}}
{{else}}
| **Contributor** | **Issues** | **Contributions** |
|-----------------|------------|-------------------|
| *Data not available* | - | - |
{{end}}

### 🎭 Contributor Roles
{{if .ContributorRoles}}
{{range .ContributorRoles}}
- **{{.Role}}**: {{range $i, $contributor := .Contributors}}{{if $i}}, {{end}}{{$contributor}}{{end}}
{{end}}
{{else}}
- **Maintainers**: *Not specified*
- **Core Contributors**: *Not specified*
- **Community Contributors**: *Not specified*
{{end}}

---

## 📊 Project Statistics

### 📈 Activity Metrics
| **Metric** | **Value** | **Trend** |
|------------|-----------|-----------|
| **Issues per Month** | {{printf "%.1f" .ActivityMetrics.IssuesPerMonth}} | {{if .ActivityMetrics.Trend}}{{.ActivityMetrics.Trend}}{{else}}📊{{end}} |
| **Avg Resolution Time** | {{printf "%.1f" .ActivityMetrics.AvgResolutionDays}} days | {{if .ActivityMetrics.ResolutionTrend}}{{.ActivityMetrics.ResolutionTrend}}{{else}}📊{{end}} |
| **Response Time** | {{printf "%.1f" .ActivityMetrics.AvgResponseHours}} hours | {{if .ActivityMetrics.ResponseTrend}}{{.ActivityMetrics.ResponseTrend}}{{else}}📊{{end}} |
| **Resolution Rate** | {{printf "%.1f" .ActivityMetrics.ResolutionRate}}% | {{if ge .ActivityMetrics.ResolutionRate 80}}✅{{else if ge .ActivityMetrics.ResolutionRate 60}}⚠️{{else}}🔴{{end}} |

### 🎯 Health Indicators
{{if .HealthIndicators}}
{{range .HealthIndicators}}
- **{{.Name}}**: {{.Value}} {{.Status}}
{{end}}
{{else}}
- **Overall Health**: {{if .OverallHealth}}{{.OverallHealth}}{{else}}Good{{end}}
- **Issue Backlog**: {{if .IssueBacklog}}{{.IssueBacklog}}{{else}}Manageable{{end}}
- **Community Activity**: {{if .CommunityActivity}}{{.CommunityActivity}}{{else}}Active{{end}}
{{end}}

---

## 🛠️ Development Workflow

### 📋 Issue Lifecycle
1. **New** → Issue created
2. **Triaged** → Labeled and prioritized
3. **In Progress** → Work started
4. **Review** → Solution under review
5. **Closed** → Resolved or declined

### 🔄 Common Workflows
{{if .CommonWorkflows}}
{{range .CommonWorkflows}}
#### {{.Name}}
{{.Description}}

**Steps:**
{{range $i, $step := .Steps}}
{{add $i 1}}. {{$step}}
{{end}}
{{end}}
{{else}}
#### Bug Fix Workflow
1. Reproduce the issue
2. Identify root cause
3. Implement fix
4. Test thoroughly
5. Submit for review

#### Feature Development
1. Discuss requirements
2. Design solution
3. Implement feature
4. Add tests
5. Update documentation
{{end}}

---

## 📖 Knowledge Base

### 🔗 Important Links
{{if .ImportantLinks}}
{{range .ImportantLinks}}
- **[{{.Title}}]({{.URL}})**: {{.Description}}
{{end}}
{{else}}
- **[Issues](../issues)**: Browse and create issues
- **[Pull Requests](../pulls)**: View code changes
- **[Wiki](../wiki)**: Project documentation
- **[Releases](../releases)**: Version history
{{end}}

### 📚 Documentation Sections
{{if .DocumentationSections}}
{{range .DocumentationSections}}
- **[{{.Title}}]({{.Link}})**: {{.Description}} ({{.PageCount}} pages)
{{end}}
{{else}}
- **[Getting Started](Home)**: Project overview and quick start
- **[Issues Summary](Issues-Summary)**: Detailed issue analysis
- **[Statistics Dashboard](Statistics)**: Project metrics and analytics
- **[Troubleshooting Guide](Troubleshooting-Guide)**: Common problems and solutions
{{end}}

### 🔍 Search Tips
` + "```" + `
# Find critical bugs
label:bug label:critical state:open

# Recent activity
updated:>2024-01-01

# Specific areas
label:frontend OR label:backend

# Documentation issues
label:documentation

# Help wanted
label:"help wanted" OR label:"good first issue"
` + "```" + `

---

## 🎭 Project Culture

### 💬 Communication Style
{{if .CommunicationGuidelines}}
{{range .CommunicationGuidelines}}
- **{{.Aspect}}**: {{.Description}}
{{end}}
{{else}}
- **Be Respectful**: Maintain professional and respectful communication
- **Be Clear**: Provide clear, detailed descriptions
- **Be Patient**: Allow time for responses and reviews
- **Be Helpful**: Support other community members
{{end}}

### 🤝 Contribution Guidelines
{{if .ContributionGuidelines}}
{{range .ContributionGuidelines}}
- **{{.Category}}**: {{.Description}}
{{end}}
{{else}}
- **Code Quality**: Follow project coding standards
- **Testing**: Include tests with code changes
- **Documentation**: Update docs for new features
- **Commit Messages**: Use clear, descriptive commit messages
{{end}}

---

## 🚨 Emergency Contacts

### 🆘 Critical Issues
{{if .EmergencyContacts}}
{{range .EmergencyContacts}}
- **{{.Role}}**: {{.Contact}} ({{.Availability}})
{{end}}
{{else}}
- **Security Issues**: Create issue with ` + "`security`" + ` label
- **Production Issues**: Create issue with ` + "`critical`" + ` label
- **General Support**: Create issue with appropriate labels
{{end}}

### 📞 Support Channels
{{if .SupportChannels}}
{{range .SupportChannels}}
- **{{.Name}}**: {{.Description}} - {{.Link}}
{{end}}
{{else}}
- **GitHub Issues**: Primary support channel
- **Discussions**: Community Q&A
- **Documentation**: Self-service help
{{end}}

---

## 🔄 Last Updated

- **Generated**: {{.GeneratedAt.Format "2006-01-02 15:04:05"}}
- **Data Period**: {{if .DataPeriod}}{{.DataPeriod}}{{else}}All available data{{end}}
- **Next Update**: {{if .NextUpdate}}{{.NextUpdate.Format "2006-01-02"}}{{else}}Automatic on wiki regeneration{{end}}

---

## 🔗 Navigation

**📊 Analytics:**
- [📊 Statistics Dashboard](Statistics) - Comprehensive project analytics
- [🏷️ Label Analysis](Label-Analysis) - Tag and categorization insights
- [📋 Processing Logs](Processing-Logs) - System monitoring and logs

**📚 Documentation:**
- [🏠 Home](Home) - Main knowledge base index
- [📋 Issues Summary](Issues-Summary) - Detailed issue listing
- [🛠️ Troubleshooting Guide](Troubleshooting-Guide) - Problem resolution

**🔗 External:**
- [📋 Issues](../issues) - Live issue tracker
- [📊 Insights](../pulse) - GitHub analytics
- [🔄 Actions](../actions) - CI/CD pipeline status

---

*📌 This quick reference is automatically generated from project data. For real-time information, visit the GitHub repository directly.*

*Generated with 📚 by Beaver AI Reference Engine - Your quick guide to project essentials*
`

const processingLogsTemplate = `# 📊 {{.ProjectName}} - Processing Logs & Monitoring

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 🧭 Current Location
📊 **Processing Logs & Monitoring**

---

## 🚀 System Overview

| **Property** | **Details** |
|--------------|-------------|
| **Project Name** | {{.ProjectName}} |
| **Processing Status** | {{if .SystemHealth.Overall}}{{.SystemHealth.Overall}}{{else}}✅ Operational{{end}} |
| **Last Update** | {{.GeneratedAt.Format "2006-01-02 15:04:05"}} |
| **Total Processed Items** | {{.ProcessingStats.TotalProcessed}} |
| **Success Rate** | {{printf "%.1f" .ProcessingStats.SuccessRate}}% |
| **Uptime** | {{if .SystemHealth.Uptime}}{{.SystemHealth.Uptime}}{{else}}Running{{end}} |

---

## 📈 Processing Statistics

### 🎯 Current Batch Performance
| **Metric** | **Value** | **Status** |
|------------|-----------|------------|
| **Items Processed** | {{.ProcessingStats.TotalProcessed}} | {{if ge .ProcessingStats.TotalProcessed 100}}✅{{else if ge .ProcessingStats.TotalProcessed 50}}⚠️{{else}}🔴{{end}} |
| **Success Rate** | {{printf "%.1f" .ProcessingStats.SuccessRate}}% | {{if ge .ProcessingStats.SuccessRate 95}}✅{{else if ge .ProcessingStats.SuccessRate 80}}⚠️{{else}}🔴{{end}} |
| **Error Rate** | {{printf "%.1f" .ProcessingStats.ErrorRate}}% | {{if le .ProcessingStats.ErrorRate 5}}✅{{else if le .ProcessingStats.ErrorRate 15}}⚠️{{else}}🔴{{end}} |
| **Average Processing Time** | {{printf "%.2f" .ProcessingStats.AvgProcessingTime}}s | {{if le .ProcessingStats.AvgProcessingTime 5}}✅{{else if le .ProcessingStats.AvgProcessingTime 15}}⚠️{{else}}🔴{{end}} |
| **Throughput** | {{printf "%.1f" .ProcessingStats.ItemsPerSecond}} items/sec | {{if ge .ProcessingStats.ItemsPerSecond 2}}✅{{else if ge .ProcessingStats.ItemsPerSecond 1}}⚠️{{else}}🔴{{end}} |

### 📊 Processing Breakdown
{{if .ProcessingStats.ByType}}
{{range .ProcessingStats.ByType}}
- **{{.Type}}**: {{.Count}} items ({{printf "%.1f" .SuccessRate}}% success)
{{end}}
{{else}}
- **Issues**: Processing count not available
- **Labels**: Processing count not available
- **Templates**: Processing count not available
{{end}}

---

## 🔄 Recent Processing Activity

### ⏰ Last 24 Hours
{{if .RecentActivity}}
| **Time** | **Operation** | **Status** | **Duration** | **Description** |
|----------|---------------|------------|--------------|-----------------|
{{range .RecentActivity}}
| **{{.Timestamp.Format "15:04:05"}}** | {{.Operation}} | {{if eq .Status "success"}}✅{{else if eq .Status "warning"}}⚠️{{else}}🔴{{end}} {{.Status}} | {{.Duration}}ms | {{.Description}} |
{{end}}
{{else}}
| **Time** | **Operation** | **Status** | **Duration** | **Description** |
|----------|---------------|------------|--------------|-----------------|
| *No recent activity logged* | - | - | - | - |
{{end}}

### 📈 Processing Trends
{{if .ProcessingTrends}}
{{range .ProcessingTrends}}
- **{{.Period}}**: {{.Count}} operations ({{printf "%.1f" .SuccessRate}}% success, avg {{printf "%.1f" .AvgDuration}}ms)
{{end}}
{{else}}
- **This Hour**: Processing trend data not available
- **Today**: Processing trend data not available
- **This Week**: Processing trend data not available
{{end}}

---

## 🚨 Error Analysis

### ⚠️ Recent Errors
{{if .Errors}}
{{range .Errors}}
#### 🔴 {{.Type}} - {{.Timestamp.Format "2006-01-02 15:04:05"}}
**Message**: {{.Message}}
**Context**: {{.Context}}
{{if .StackTrace}}**Stack Trace**: ` + "```{{.StackTrace}}```" + `{{end}}
**Resolution**: {{if .Resolution}}{{.Resolution}}{{else}}Under investigation{{end}}

---
{{end}}
{{else}}
#### ✅ No Recent Errors
The system is currently operating without errors.
{{end}}

### 📊 Error Patterns
{{if .ErrorPatterns}}
{{range .ErrorPatterns}}
- **{{.Pattern}}**: {{.Count}} occurrences ({{.Description}})
{{end}}
{{else}}
- No error patterns detected in recent processing
{{end}}

### 🔧 Error Resolution Status
{{if .ErrorResolution}}
{{range .ErrorResolution}}
- **{{.Type}}**: {{.Status}} ({{.Count}} instances)
{{end}}
{{else}}
- **API Errors**: ✅ No recent issues
- **Processing Errors**: ✅ No recent issues
- **Template Errors**: ✅ No recent issues
- **File System Errors**: ✅ No recent issues
{{end}}

---

## 🎯 System Health Indicators

### 🏥 Core Components
{{if .SystemHealth.Components}}
{{range .SystemHealth.Components}}
- **{{.Name}}**: {{.Status}} {{if eq .Status "healthy"}}✅{{else if eq .Status "warning"}}⚠️{{else}}🔴{{end}} ({{.LastCheck.Format "15:04:05"}})
{{end}}
{{else}}
- **GitHub API**: ✅ Healthy (Rate limits within bounds)
- **AI Processing**: ✅ Healthy (Response times normal)
- **Template Engine**: ✅ Healthy (Rendering successful)
- **File System**: ✅ Healthy (Disk space sufficient)
- **Memory Usage**: ✅ Healthy (Within normal limits)
{{end}}

### 📡 External Dependencies
{{if .ExternalDependencies}}
| **Service** | **Status** | **Response Time** | **Last Check** |
|-------------|------------|-------------------|----------------|
{{range .ExternalDependencies}}
| **{{.Name}}** | {{.Status}} {{if eq .Status "online"}}✅{{else if eq .Status "degraded"}}⚠️{{else}}🔴{{end}} | {{.ResponseTime}}ms | {{.LastCheck.Format "15:04:05"}} |
{{end}}
{{else}}
| **Service** | **Status** | **Response Time** | **Last Check** |
|-------------|------------|-------------------|----------------|
| **GitHub API** | ✅ Online | <100ms | Just now |
| **OpenAI API** | ✅ Online | <2000ms | Just now |
| **Anthropic API** | ✅ Online | <2000ms | Just now |
{{end}}

---

## 🔧 Performance Metrics

### ⚡ Speed Analysis
{{if .PerformanceMetrics}}
- **Template Rendering**: {{printf "%.2f" .PerformanceMetrics.TemplateRenderingTime}}ms avg
- **Data Processing**: {{printf "%.2f" .PerformanceMetrics.DataProcessingTime}}ms avg
- **API Calls**: {{printf "%.2f" .PerformanceMetrics.APICallTime}}ms avg
- **File Operations**: {{printf "%.2f" .PerformanceMetrics.FileOperationTime}}ms avg
{{else}}
- **Template Rendering**: <50ms avg (Excellent)
- **Data Processing**: <200ms avg (Good)
- **API Calls**: <1000ms avg (Normal)
- **File Operations**: <10ms avg (Excellent)
{{end}}

### 💾 Resource Usage
{{if .ResourceUsage}}
- **Memory Usage**: {{printf "%.1f" .ResourceUsage.MemoryMB}}MB ({{printf "%.1f" .ResourceUsage.MemoryPercent}}% of available)
- **CPU Usage**: {{printf "%.1f" .ResourceUsage.CPUPercent}}% avg
- **Disk Usage**: {{printf "%.1f" .ResourceUsage.DiskUsageMB}}MB processed data
- **Network**: {{printf "%.1f" .ResourceUsage.NetworkKB}}KB transferred
{{else}}
- **Memory Usage**: Normal (within expected limits)
- **CPU Usage**: Low to moderate (efficient processing)
- **Disk Usage**: Minimal (optimized storage)
- **Network**: Efficient (minimal API calls)
{{end}}

---

## 🔗 Navigation

**📊 Analytics:**
- [📊 Statistics Dashboard](Statistics) - Comprehensive project analytics
- [🏷️ Label Analysis](Label-Analysis) - Tag and categorization insights
- [📚 Quick Reference](Quick-Reference) - Essential project information

**📚 Documentation:**
- [🏠 Home](Home) - Main knowledge base index
- [📋 Issues Summary](Issues-Summary) - Detailed issue listing
- [🛠️ Troubleshooting Guide](Troubleshooting-Guide) - Problem resolution

**🔗 External:**
- [📋 Issues](../issues) - Live issue tracker
- [📊 Insights](../pulse) - GitHub analytics
- [🔄 Actions](../actions) - CI/CD pipeline status

---

*📊 This monitoring dashboard provides real-time insights into the Beaver AI processing system. For alerts or issues, check the system health section or consult the troubleshooting guide.*

*Generated with 🔍 by Beaver AI Monitoring Engine - Your window into system performance*
`

// GetDefaultTemplateContent returns the content of a default template
func GetDefaultTemplateContent(templateName string) (string, bool) {
	templates := map[string]string{
		"issues-summary":  issuesSummaryTemplate,
		"troubleshooting": troubleshootingTemplate,
		"learning-path":   learningPathTemplate,
		"index":           indexTemplate,
		"statistics":      statisticsTemplate,
		"label-analysis":  labelAnalysisTemplate,
		"quick-reference": quickReferenceTemplate,
		"processing-logs": processingLogsTemplate,
	}

	content, exists := templates[templateName]
	return content, exists
}
