package wiki

import (
	"fmt"
	"text/template"
)

// TemplateManager manages Wiki generation templates
type TemplateManager struct {
	templates map[string]*template.Template
}

// NewTemplateManager creates a new template manager
func NewTemplateManager() *TemplateManager {
	tm := &TemplateManager{
		templates: make(map[string]*template.Template),
	}
	tm.loadDefaultTemplates()
	return tm
}

// LoadTemplate loads a template from string
func (tm *TemplateManager) LoadTemplate(name, content string) error {
	tmpl, err := template.New(name).Parse(content)
	if err != nil {
		return fmt.Errorf("failed to parse template %s: %w", name, err)
	}
	tm.templates[name] = tmpl
	return nil
}

// GetTemplate returns a template by name
func (tm *TemplateManager) GetTemplate(name string) (*template.Template, bool) {
	tmpl, exists := tm.templates[name]
	return tmpl, exists
}

// loadDefaultTemplates loads built-in templates
func (tm *TemplateManager) loadDefaultTemplates() {
	// Issues Summary Template
	_ = tm.LoadTemplate("issues-summary", issuesSummaryTemplate) //nolint:errcheck // Default templates

	// Troubleshooting Guide Template
	_ = tm.LoadTemplate("troubleshooting", troubleshootingTemplate) //nolint:errcheck // Default templates

	// Learning Path Template
	_ = tm.LoadTemplate("learning-path", learningPathTemplate) //nolint:errcheck // Default templates

	// Index Template
	_ = tm.LoadTemplate("index", indexTemplate) //nolint:errcheck // Default templates
}

// RegisterTemplate registers a custom template
func (tm *TemplateManager) RegisterTemplate(name, content string) error {
	return tm.LoadTemplate(name, content)
}

// ListTemplates returns all available template names
func (tm *TemplateManager) ListTemplates() []string {
	var names []string
	for name := range tm.templates {
		names = append(names, name)
	}
	return names
}

// Template content definitions

const issuesSummaryTemplate = `# 📋 {{.ProjectName}} - Issues Summary

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 📊 Overview

- **Total Issues**: {{.TotalIssues}}
- **Open Issues**: {{.OpenIssues}}
- **Closed Issues**: {{.ClosedIssues}}
- **AI Processor**: {{.AIProcessor}}
- **Beaver Version**: {{.BeaverVersion}}

## 🤖 AI Classification Summary

{{if gt .ClassificationStats.TotalClassified 0}}
- **Total Classified**: {{.ClassificationStats.TotalClassified}} / {{.TotalIssues}}
- **Average Confidence**: {{printf "%.2f" .ClassificationStats.AverageConfidence}}
- **High Confidence (≥0.8)**: {{.ClassificationStats.HighConfidenceCount}}
- **Low Confidence (<0.5)**: {{.ClassificationStats.LowConfidenceCount}}

### 📊 Categories Distribution
{{range $category, $count := .ClassificationStats.ByCategory}}
- **{{$category}}**: {{$count}} issue(s)
{{end}}

### 🔧 Classification Methods
{{range $method, $count := .ClassificationStats.ByMethod}}
- **{{$method}}**: {{$count}} issue(s)
{{end}}

### 🏷️ Most Common Tags
{{if .ClassificationStats.MostCommonTags}}{{range $i, $tag := .ClassificationStats.MostCommonTags}}{{if $i}}, {{end}}` + "`{{$tag}}`" + `{{end}}{{end}}
{{else}}
- **No AI classification data available**
- Run ` + "`beaver classify`" + ` to generate AI classifications
{{end}}

## 📝 Issues List

{{range .Issues}}
### 🔸 Issue #{{.Number}}: {{.Title}}

**Status**: {{if eq .State "open"}}🟡 Open{{else}}✅ Closed{{end}}
**Created**: {{.CreatedAt.Format "2006-01-02"}}
**Updated**: {{.UpdatedAt.Format "2006-01-02"}}
**Author**: {{.User}}

{{if .Classification}}
**🤖 AI Classification**:
- **Category**: ` + "`{{.Classification.Category}}`" + ` ({{printf "%.2f" .Classification.Confidence}} confidence)
- **Method**: {{.Classification.Method}}
- **Reasoning**: {{.Classification.Reasoning}}
{{if .Classification.SuggestedTags}}- **Suggested Tags**: {{range $i, $tag := .Classification.SuggestedTags}}{{if $i}}, {{end}}` + "`{{$tag}}`" + `{{end}}{{end}}
- **Classified**: {{.Classification.ClassifiedAt.Format "2006-01-02 15:04"}}
{{end}}

{{if .Labels}}**Labels**: {{range $i, $label := .Labels}}{{if $i}}, {{end}}` + "`{{$label}}`" + `{{end}}{{end}}

**Description**:
{{if gt (len .Body) 200}}{{slice .Body 0 200}}...{{else}}{{.Body}}{{end}}

{{if .Comments}}
**Comments**: {{len .Comments}} comment(s)
{{end}}

---

{{end}}

## 🔗 Navigation

- [🏠 Home](Home)
- [🛠️ Troubleshooting Guide](Troubleshooting-Guide)
- [📚 Learning Path](Learning-Path)

---

**📌 Note**: This summary was automatically generated from GitHub Issues using Beaver AI processing.
`

const troubleshootingTemplate = `# 🛠️ {{.ProjectName}} - Troubleshooting Guide

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 📋 Overview

This guide contains solutions and troubleshooting information extracted from **{{len .SolvedIssues}} solved issues**.

## 🔧 Common Error Patterns

{{range .CommonErrors}}
### ❌ {{.Pattern}}

**Description**: {{.Description}}
**Frequency**: {{.Frequency}} occurrence(s)

**Solutions**:
{{range .Solutions}}
- {{.}}
{{end}}

---

{{end}}

## ✅ Documented Solutions

{{range .Solutions}}
### 💡 {{.Title}}

{{.Description}}

**Steps**:
{{range .Steps}}
1. {{.}}
{{end}}

**Related Issues**: {{range $i, $issue := .RelatedIssues}}{{if $i}}, {{end}}#{{$issue}}{{end}}

---

{{end}}

## 📋 Solved Issues Reference

{{range .SolvedIssues}}
### ✅ #{{.Number}}: {{.Title}}

**Solved**: {{.UpdatedAt.Format "2006-01-02"}}
**Resolution**: {{if gt (len .Body) 150}}{{slice .Body 0 150}}...{{else}}{{.Body}}{{end}}

{{if .Labels}}**Tags**: {{range $i, $label := .Labels}}{{if $i}}, {{end}}` + "`{{$label}}`" + `{{end}}{{end}}

{{end}}

## 🚨 Quick Fixes

### Common Issues
- Check configuration files
- Verify API keys and environment variables
- Review log files for detailed error messages
- Ensure all dependencies are properly installed

### Debug Steps
1. Enable debug logging
2. Check system requirements
3. Verify network connectivity
4. Test with minimal configuration

## 🔗 Navigation

- [🏠 Home](Home)
- [📋 Issues Summary](Issues-Summary)
- [📚 Learning Path](Learning-Path)

---

**📌 Note**: Solutions are extracted from resolved GitHub Issues. For detailed context, refer to the original issue numbers.
`

const learningPathTemplate = `# 📚 {{.ProjectName}} - Learning Path

> 🤖 Generated by Beaver AI on {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## 🎯 Development Journey

This learning path is extracted from the project's evolution through GitHub Issues and implementation milestones.

## 🏁 Milestones

{{range .Milestones}}
### 🚩 {{.Name}}

{{.Description}}

{{if .CompletedAt}}**Completed**: {{.CompletedAt.Format "2006-01-02"}}{{else}}**Status**: In Progress{{end}}

**Issues**: {{len .Issues}} issue(s)
{{range .Issues}}
- [#{{.Number}}: {{.Title}}](../issues/{{.Number}})
{{end}}

**Key Learnings**:
{{range .Learnings}}
- {{.}}
{{end}}

---

{{end}}

## 💻 Technologies & Skills

{{range .Technologies}}
### 🔧 {{.Name}}

{{.Description}}

**Used in**:
{{range .UsedIn}}
- {{.}}
{{end}}

**Resources**:
{{range .Resources}}
- {{.}}
{{end}}

---

{{end}}

## 🎯 Learning Goals

{{range .LearningGoals}}
### 📖 {{.Title}}

{{.Description}}

**Status**: {{.Status}}
**Progress**: {{.Progress}}%

{{if eq .Status "Completed"}}✅{{else if eq .Status "In Progress"}}🔄{{else}}⏳{{end}} {{.Progress}}% Complete

**Related Issues**: {{range $i, $issue := .RelatedIssues}}{{if $i}}, {{end}}#{{$issue}}{{end}}

---

{{end}}

## 📈 Growth Areas

### Technical Skills
- Software architecture and design patterns
- API development and integration
- Testing and quality assurance
- DevOps and deployment strategies

### Soft Skills
- Problem-solving methodology
- Documentation and communication
- Project planning and execution
- Code review and collaboration

## 🎓 Next Steps

1. **Review completed milestones** for key insights
2. **Identify knowledge gaps** from current issues
3. **Plan learning objectives** for upcoming features
4. **Document lessons learned** for future reference

## 🔗 Navigation

- [🏠 Home](Home)
- [📋 Issues Summary](Issues-Summary)
- [🛠️ Troubleshooting Guide](Troubleshooting-Guide)

---

**📌 Note**: This learning path is dynamically generated from project activity and should be reviewed regularly.
`

const indexTemplate = `# 🦫 {{.ProjectName}} - Knowledge Dam

> 🤖 Powered by Beaver AI - Transforming development streams into structured knowledge

Welcome to the **{{.ProjectName}}** knowledge base! This Wiki is automatically generated from GitHub Issues using AI processing to create structured documentation.

## 📚 Documentation Sections

### 📋 [Issues Summary](Issues-Summary)
Complete overview of all GitHub Issues with AI-generated summaries and categorization.

### 🛠️ [Troubleshooting Guide](Troubleshooting-Guide)
Solutions and fixes extracted from resolved issues, organized by problem patterns.

### 📚 [Learning Path](Learning-Path)
Development journey and milestones extracted from project evolution.

## 🤖 AI Processing

This documentation is generated using:
- **OpenAI/Anthropic APIs** for content analysis
- **Pattern recognition** for categorization
- **Semantic analysis** for knowledge extraction
- **Template-based generation** for consistent formatting

## 📊 Statistics

- **Generated**: {{.GeneratedAt.Format "2006-01-02 15:04:05"}}
- **Total Issues**: {{.TotalIssues}}
- **Processing Status**: {{.Status}}
- **Last Update**: {{.LastUpdate.Format "2006-01-02 15:04:05"}}

## 🔄 Auto-Update

This Wiki is automatically updated when:
- New issues are created or updated
- Issues are closed or resolved
- AI processing reveals new patterns
- Project milestones are reached

## 🎯 Purpose

The Beaver Knowledge Dam serves to:
1. **Preserve Knowledge**: Prevent valuable insights from being lost
2. **Accelerate Learning**: Provide structured learning paths
3. **Improve Debugging**: Offer quick access to solutions
4. **Track Progress**: Document development evolution

## 🔧 Configuration

Wiki generation can be customized through:
- Template modifications
- Category definitions
- Processing rules
- Output formats

## 📞 Support

For issues with Wiki generation:
1. Check the [Troubleshooting Guide](Troubleshooting-Guide)
2. Review the original GitHub Issues
3. Verify Beaver AI configuration
4. Submit feedback through project issues

---

**🚀 Ready to explore your project's knowledge! Navigate using the links above.**
`

// GetDefaultTemplateContent returns the content of a default template
func GetDefaultTemplateContent(templateName string) (string, bool) {
	templates := map[string]string{
		"issues-summary":  issuesSummaryTemplate,
		"troubleshooting": troubleshootingTemplate,
		"learning-path":   learningPathTemplate,
		"index":           indexTemplate,
	}

	content, exists := templates[templateName]
	return content, exists
}
