name: Dependency Review

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD
          deny-licenses: GPL-2.0, GPL-3.0, LGPL-2.1, LGPL-3.0, AGPL-3.0
          comment-summary-in-pr: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check for known vulnerabilities
        run: npm audit --audit-level=moderate
        
      - name: Generate dependency report
        run: |
          echo "# Dependency Report" > dependency-report.md
          echo "" >> dependency-report.md
          echo "## Package Summary" >> dependency-report.md
          npm ls --depth=0 --json | jq -r '.dependencies | keys | .[] | "- \(.)"' >> dependency-report.md
          echo "" >> dependency-report.md
          echo "## Security Audit" >> dependency-report.md
          npm audit --json | jq -r '.vulnerabilities | keys | .[] | "- \(.)"' >> dependency-report.md || echo "No vulnerabilities found" >> dependency-report.md
          
      - name: Comment PR with dependency report
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('dependency-report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📦 **Dependency Review Report**\n\n${report}`
            })